from . import start
from . import emergency_help_ru
from . import emergency_help_uz
from . import condition_assessment_ru
from . import condition_assessment_uz
from . import help
from . import echo
from . import registration_ru
from . import registration_uz
